NAME = libft.a
CC  = gcc 
cFlag = -Wall -Wextra -Werror 
AR = ar rcs


SRC = ft_isalpha.c \
ft_isascii.c \
ft_isdigit.c \
ft_isprint.c \
	
all:
	@cc -Wall -Wextra -Werror $(NAME) -o $(NAME).out
	@./$(NAME).out

norm:
	norminette $(SRC)

clean:

fclean:

re:



